### ISSUE TITLE
should Response.Body be an io.ReadCloser?

### ISSUE THREAD

**Issue by ianh** [prologic/go-gopher#14]
Hello; I'm writing a Go program that can read from multiple protocols including HTTP and Gopher.  The builtin net/http provides an `io.ReadCloser` as its response body, but `gopher.Response.Body` is just an `io.Reader`.  Is there a reason for this inconsistency?  It's frustrating to have to wrap the `io.Reader` just to implement a do-nothing `Close` method.  It also seems useful to be able to close the connection to the server without having read the entire response body.

**Comment by ianh** [comment]
I made this change in my own fork (https://github.com/ianh/go-gopher/tree/read-closer) — let me know if you'd like me to make a pull request.

**Comment by prologic** [comment]
Yeah no reason I can think of! Please submit a PR to fix this 🙇‍♀️

**Comment by ianh** [comment]
Done! #15

**Comment by prologic** [comment]
Thank you! 🙇‍♀️

**Comment by ianh** [comment]
No problem, thanks for the useful package!
